language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - PHPCS=0
    - RUN_TESTS=1

services:
  - elasticsearch

addons:
  apt:
    sources:
      - elasticsearch-2.1
    packages:
      - elasticsearch

matrix:
  include:
    - php: 5.6
      env: PHPCS=1 RUN_TESTS=0

before_script:
  - sleep 7 # Work around elasticsearch startup time.
  - phpenv rehash

install:
  - composer self-update
  - composer install --dev

script:
  - sh -c "if [ '$RUN_TESTS' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"

notifications:
  email: false
